services:
  - type: worker
    name: hi2-checker-bot
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium

    startCommand: python bot.py
